language: node_js
node_js:
  - "16.13"
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:

- npm run build --prod --base-href https://github.com/VineethaPR/hello-world/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/hello-world
  on:
    branch: master