language: node_js
node_js:
  - "16.13"
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli

script:
  - npm run test:headless

before_deploy:
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/hello-world
  on:
    branch: master